### ISSUE TITLE
mrview: show overlay value

### ISSUE THREAD

**Issue by dafnis** [jdtournier/mrtrix3#157]
Could implement a way to see the values of the overlays in the actual cross-hair position?

That would be very useful to check values of labels and segmentations over a background image.

**Comment by Lestropie** [comment]
* You could try using the overlay image path basename as the popup text.
* Probably want to toggle the image sampling between nearest-neighbour and trilinear interpolation depending on whether or not the overlay itself is interpolated.

**Comment by rtabbara** [comment]
Done and done. The base image was exclusively using nearest-neighbour interp. to fetch the label value, so that was similarly changed to use trilinear/nearest-neighbour depending on whether or not image itself is interpolated. Not sure whether that's the desired behaviour.

**Comment by dafnis** [comment]
The behaviour of the popup value is switched, i.e., it shows triinear interpolated value when showing NOT interpolated image/overlay, and nearest neighbour when image/overlay is interpolated. 

Note that now this happens with both the base image and the overlays.
