### ISSUE TITLE
Wiki: FAQ

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#164]
Should create an FAQ page in the wiki that people can search for, to ensure that questions have not been covered previously.

Possible inclusions (feel free to add to):
* Processing of HCP data
* Generating TW-FC maps
* Unfixed issues e.g. Windows claiming improper termination of mrview
* Installation issues - these could possibly be in a separate page, or anything specific to a particular OS could appear at the end of the relevant existing page
* Including spinal projections in the connectome
* Checking registrations - flicking between images v.s. overlay tool

**Comment by jdtournier** [comment]
Agreed. I also think OS-specific issues should be handled within that OS's installation page. 

I'll create a FAQ folder on the wiki to house all this stuff. By the way, this requires a little bit of faffing about to get right, in terms of keeping the table of contents in the sidebar small. What I want to do is have a FAQ section listed as a single item in the sidebar of the main pages, and have a different sidebar with all the FAQ entries listed when viewing FAQ entries. To do this, you need to clone the wiki (it's a git repo), add a folder, create a custom `_Sidebar.md`, and add your FAQ entries in there. GitHub will then display the sidebar within the page's folder, which is the desired effect. I've just done this for the command listing, I'll set it up for the FAQ, and add in some empty pages for the topics you've listed so far. Hopefully that means you can start editing them without them going in the wrong folder...

**Comment by jdtournier** [comment]
OK, done. There's 3 empty FAQ pages to be filled out...

**Comment by jdtournier** [comment]
Closing this for now - although we still need to fill in these FAQ entries...
