### ISSUE TITLE
mrview: Implement parula colormap

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#165]
Is now the default in Matlab, is likely to become popular.

**Comment by Lestropie** [comment]
Hmmm. Actually, apparently it's MathWorks IP and can't be legally reproduced...

**Comment by jdtournier** [comment]
Close this...?

**Comment by Lestropie** [comment]
Yeah probably gotta wait and see if MathWorks make it open. Plus I googled 'parula colormap legal' and this issue showed up as result number 5, so I doubt we'd get away with just implementing it.

**Comment by draffelt** [comment]
Let's close it and reopen in the future if possible. It's a shame. It's a
great colour map. Converts to grey scale intensities when printed black and
white perfectly.

On Fri, Mar 13, 2015 at 1:07 AM, J-Donald Tournier <notifications@github.com

**Comment by Lestropie** [comment]
#openparula

**Comment by maxpietsch** [comment]
DIY parula for long winter evenings: http://www.sandia.gov/~kmorel/documents/ColorMaps/

**Comment by Lestropie** [comment]
A possible alternative here would be [viridis](https://bids.github.io/colormap/), which is the default in `matplotlib` and has an open-source [lookup table](https://github.com/BIDS/colormap/blob/master/colormaps.py). It would however require either approximating the RGB curves using polynomials, or implementing the capability to upload the table to the GPU.

**Comment by lconcha** [comment]
Sorry for bringing this back from the dead. I lieu of the capability to add custom color maps in a straightforward manner, perhaps you could add a couple of divergent color maps? They are most useful to search for differences between groups. Cheers.

**Comment by Lestropie** [comment]
I'd really like to have custom colour maps; we're just really struggling for dev resources right now.

You can kind of cheat to get divergent colour maps by loading the same image as an overlay twice, one with a lower threshold of 0, the other with an upper threshold of 0 and inverted colour map. But you'd still be limited on each side independently by the existing colour maps, or fixed colours for which the lower end of the map will tend to black.
