### ISSUE TITLE
New ProgressBar hanging

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#166]
Need to figure out exact circumstances, but every now and then the progress bar will sit there re-printing the line and forbidding the program from progressing. Running with the -quiet option works fine.

**Comment by jdtournier** [comment]
That would not be cool. Would be good to get to the bottom of it. Just to narrow things down, did this happen with the percentage status or the busy indicator? And was it using the new update() method?

**Comment by jdtournier** [comment]
Sorry, my bad, the new ProgressBar code is still in the `log_to_file` branch. Shouldn't be an issue assuming you're running on the master branch (?). 

Could it be your terminal doing something funny? Are you still using Terminator or whatever it's called...?
