### ISSUE TITLE
Config option to bypass VT100 codes

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#168]
In the terminal emulator provided with Git on Windows, was getting weird codes appearing in the terminal, probably either VT100 codes or colour codes. Should add a config file option to use 'plain' text and just '\r' for carriage return.

**Comment by jdtournier** [comment]
There is one: TerminalColour - see `lib/exception.cpp`, line 60 or so. Even documented it, for once...

It still allows the line clear code though, in addition to the carriage return. Hopefully that won't cause any issues...?

**Comment by Lestropie** [comment]
Setting TerminalColor to false removes most of them, but not all: there's still a '<-[2K' at the end of progress bars.

I'm thinking of changing the 'TerminalColor' conf option to something like 'SimpleTerminal', and using it to disable both terminal colours and line clears.

**Comment by jdtournier** [comment]
Crap. The problem with that is that when using the ProgressBar update() or set_text() methods, you get dangling characters at the end if the string becomes shorter.

A better approach would be to figure out the correct codes for that terminal. Maybe `tput` can help us to get this right...?

**Comment by Lestropie** [comment]
Well the dangling strings would be no worse than what we could have had previously without the VT100 code. Alternatively we could store the number of characters in the current message, and if SimpleTerminal is enabled and the new message is shorter than the old one, append with spaces.

**Comment by jdtournier** [comment]
Strange... I just tried this on my Windows VM (Windows 7 64 bit), and I get the same as you. However, everything seems to work OK when using these codes directly on the command-line, e.g.:

```ShellSession
$ echo -e "first line to be cleared\r\033[2Knext line"
next line
```

Or the approach in the current `log_to_file` branch (clear from current position, rather than clear whole line):

```ShellSession
$ echo -e "first line to be cleared\rnext line\033[0K"
next line
```

But then if I try this in Python:
```ShellSession
$ python
>>> print 'first line to be cleared\r\033[2Knext line'
←[2Knext line to be cleared
```

Clearly bash does its own translation... 
I'll dig a little deeper and see whether we can figure something out...

**Comment by jdtournier** [comment]
OK, turns out just adding `\015` in front of the `\033[0K` or `\033[2K` codes works for the ProgressBar. Still can't get the colour codes to work. Struggling to even get the config file to load in at the moment...

**Comment by jdtournier** [comment]
Had a quick look into how the colour escape sequences are handled in msys-git, it seems they have re-implemented the `printf()`, `fprintf()`, etc calls to catch these sequences and handle them using the Windows API. There is no way I'm putting in that much work... 

I guess the simplest will be to use the control sequence `\015\033[0K` for line clear, and avoid default to no colour for the rest of the code...

**Comment by jdtournier** [comment]
OK, I've just made a couple of changes to address this in commit ef6d06f on branch `log_to_file`, which has lots of related changes and which I was going to merge anyway. See what you think...

**Comment by jdtournier** [comment]
I'll close this and leave any remaining discussion for pull request #181 ...
