### ISSUE TITLE
Volume rendering and colourmap 'colour' throws OpenGL fragment shader error

### ISSUE THREAD

**Issue by maxpietsch** [jdtournier/mrtrix3#172]
./bin/mrview image.mif  -run 'tool.open 3' -run 'overlay.load overlay.mif' -run 'view.mode 3'  throws the errors:

[ERROR] GLSL log [fragment shader]: 0(60) : error C1008: undefined variable "colourmap_colour"
followed by
[ERROR] error compiling OpenGL fragment shader ID 8

if the colourmap 'colour' is selected.

**Comment by jdtournier** [comment]
Ah, yes, I started adding support for colour-mapping using a single colour, which would be useful for the overlay tool, but never got round to finishing it off... Basically, it needs a little bit more work on the UI front to provide a means of setting the colour, probably as an additional entry in the colourmap sub-menu (which I think gets imported whole-sale into the overlay's colourmap selector). And then yes, I'd need to fix up the volume render shader to support that too...

If anyone feels like helping out, feel free... :)

**Comment by rtabbara** [comment]
I'm working on #174 so if you want I can also take a look at this.

**Comment by jdtournier** [comment]
Thanks Rami. I was hoping you'd say this... :)

**Comment by rtabbara** [comment]
@maxpietsch This should be fixed now after 902b355. Please give it a go and let me know.

**Comment by maxpietsch** [comment]
Works like a charm on my mac.
