### ISSUE TITLE
Runtime error when trying to build commands with -static configuration option

### ISSUE THREAD

**Issue by draffelt** [jdtournier/mrtrix3#176]
When running mrconvert I'm getting the following error.  

terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)

**Comment by jdtournier** [comment]
Most likely due to missing `-pthread` option in both the `cflags` and `ldflags` variables in your config (at least for the shared version). Check your `build.log`: were there options passed to gcc both at compile time and at link time? Does your config file include these options?

**Comment by jdtournier** [comment]
OK, confirmed on my end. Seems like a bug in the linker to me... 

Anyway, two ways around this:

-  use the new [standalone installation procedure](https://github.com/jdtournier/mrtrix3/wiki/linux-standalone-installation) - not recommended if you have the choice. Not sure why you need a static build, but my guess is you probably don't - you can just pluck out the executable and the MRtrix library and place them in `bin` and `lib` folders respectively anywhere you want - all executables are set up to search for libraries in the `../lib` folder relative to their own location, so it'll use the MRtrix library you've placed in that folder preferentially. Assuming you're running the same OS, and all you want is to compile a version and know that it won't change, this is what you should do. If that's what you're after, just set them up in their own folder and add them to the path (or symlink to the executable from a folder in the PATH, that works too). 

- add the `-Wl,-u,pthread_cancel,-u,pthread_cond_broadcast,-u,pthread_cond_destroy,-u,pthread_cond_signal,-u,pthread_cond_wait,-u,pthread_create,-u,pthread_detach,-u,pthread_cond_signal,-u,pthread_equal,-u,pthread_join,-u,pthread_mutex_lock,-u,pthread_mutex_unlock,-u,pthread_once,-u,pthread_setcancelstate` to the linker command line, as suggested on [this post](http://stackoverflow.com/a/27774767/3244166). Tested, works, just need to add this to the `ld_flags` variable in your `config.static` (or whatever config you used). I'm guessing the right thing to do is to add this to the `configure` script so it's in there by default, but I'll wait to hear whether this works for you first...
