### ISSUE TITLE
mrview no longer working on Windows

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#197]
Get a small error window with "Bad file descriptor". GDB is of no use. Clean build.

Edit: Crashes even before reaching `int main (int cmdline_argc, char** cmdline_argv)`

**Comment by jdtournier** [comment]
Weird. I can't think what I could have done on the global scope that would cause this specifically for MRView. Does this happen with other apps? If it was the new tmpfile prefix code (I assume that's what you're talking about?), then the only interaction there is really is a call to `getenv()`... And it shouldn't happen before `main()`. And it shouldn't be specific to MRView. Any idea which specific commit introduced the problem...?

**Comment by Lestropie** [comment]
No, still looking at it amongst other things. Specific to mrview and shview. Regardless of whether or not an image is provided at the command line, or whether any options are provided. But given it bugs out before it even calls main(), I'm not quite sure what to try next.

**Comment by Lestropie** [comment]
"Bad file descriptor" had me thinking it might be to do with the detection of stdout / stderr to a file... but how that would then be specific to GUI apps I don't know.

**Comment by jdtournier** [comment]
I guess the first thing is to figure out which commit introduced the problem. Thankfully there haven't been too many large commits recently, it should be pretty easy to sort out once we see what's changed.

**Comment by Lestropie** [comment]
Yeah, I'll work my way back slowly. It's just boring that way.

**Comment by jdtournier** [comment]
What could be more fun...?

Just had a quick look through the history for anything affecting `src/gui` - the only thing that pops up recently is the change in the handling of the version string (commit 46cdd0e), which did make a couple of changes at the global scope. Still no clue why that would cause issues _before_ entering `main()`, but worth trying just before that commit first...

**Comment by Lestropie** [comment]
15301511 is the culprit. Trouble is, I can't seem to find a way to fix it. Found some documentation suggesting that windows doesn't define STDERR_FILENO, so I tried manually defining it, even tried hardwiring app.cpp to `stderr_to_file = Path::is_file (2);`; works for everything except `mrview` and `shview` on Windows. Change that line to `stderr_to_file = false;` and it's all good. And when it doesn't work, it crashes before it even starts `main()`, so can't see what's what. Weird.

**Comment by jdtournier** [comment]
Thanks for hunting that one down (I don't have a Windows machine that'll run MRView handy, only a VM). 

That is indeed pretty freaky. This line is in `App::init()`, which _should_ only be invoked within `main()`. Really can't see how this could be happening. Only obvious thing to check is whether `STDERR_FILENO` is somehow different between the command-line apps and the GUI apps (maybe Qt redefines it or something), but that assumes it's not actually defined as 2 normally under MinGW... And even then it doesn't explain why it would crash out _before_ entering `main()` - unless the compiler is pre-computing this somewhere... Is this running in debug mode?

**Comment by Lestropie** [comment]
`STDERR_FILENO` is 2 on everything I've checked. To check it on `mrview` / `shview` I had to write it to a file; I can't see the output at the terminal no matter where I print to stderr (even if it's right at the start of `main()`, before `MR::GUI::App` construction), but it seems to still be 2. Also, problem persists if I hardwire the `is_file()` call to 2, in which case `STDERR_FILENO` is never even referenced. Independent of debug/release compilation. Tried changing `fstat()` to `_fstati64()` without success.

**Comment by jdtournier** [comment]
It seems the `fstat()` call might be a bit problematic on Windows (see e.g. [this old post](https://lists.gnu.org/archive/html/bug-gnulib/2006-06/msg00314.html)). Not sure whether this explains the problem, but might give us some pointers...

**Comment by jdtournier** [comment]
I wonder if stderr is a socket on Windows... Then this would be relevant: http://repo.or.cz/w/git/mingw.git?a=commitdiff;h=b49fa05b92a7a369beca1de67fded5a6da500f9c

**Comment by jdtournier** [comment]
Hang on, I know what's going on. In Windows, GUI apps don't get stdin/stdout/stderr - unless they're compiled to run within a terminal (when you get a terminal popping up when you launch them). There's a compiler flag you can pass to MinGW to specify that. In this case, we genuinely are calling `fstat()` on an invalid file descriptor...

**Comment by Lestropie** [comment]
This hack gets me working, will have to see if it still behaves as expected though:
```
    inline bool is_file (int file_descriptor)
    {
#ifdef MRTRIX_WINDOWS
      return close(dup(file_descriptor)) != 0;
#else
      struct stat buf;
      if (!fstat (file_descriptor, &buf)) return S_ISREG (buf.st_mode);
      throw Exception (strerror (errno));
      return false;
#endif
    }
```

**Comment by jdtournier** [comment]
I have a feeling all we need to do is check for exceptions around the `stderr_to_file = Path::is_file()` line in `app.cpp`: the error window that you see might be due to the unhandled exception thrown immediately after the `fstat()` call when it returns an error.

**Comment by Lestropie** [comment]
Ugh. My error messages weren't printing, so I assumed something was bugging out prior; it was that exception within `is_file()`.

**Comment by jdtournier** [comment]
Hehe, good work! I guess Windows never claimed to be POSIX-compliant...
