### ISSUE TITLE
Switch to /tmp as default tmpfile directory?

### ISSUE THREAD

**Issue by jdtournier** [jdtournier/mrtrix3#199]
Currently, temporary files (used in pipelines, see the [detailed docs on the topic](https://github.com/jdtournier/mrtrix3/wiki/Unix-Pipelines#how-is-it-implemented)) are written within the current working directory (unless overridden with the _TmpFileDir_ [config file option](https://github.com/jdtournier/mrtrix3/wiki/List-of-configuration-file-options)). The rationale for this choice was two-fold: give users visibility into their leftovers so they can clean up the mess produced by crashes and interrupts in pipelines (who ever looks in the `/tmp` filesystem anyway?); and avoid file size limitations when the `/tmp` filesystem is small (it used to be a prohibitively small, at least on some of the systems I came across back when). 

This can cause issues when the current folder (or the user's home folder) resides on a network filesystem. When the file is written to local storage, the system tends to hold it in RAM with delayed write-back, so it rarely even makes it to the hard drive. On network filesystems however, the system seems to force the write to proceed to completion, then reload the file over the network with the next stage of the pipeline. I'm guessing the exact behaviour will depend on the filesystem used, but clearly it's not great for performance...

Modern distributions now typically mount the `/tmp` folder on a [tmpfs filesystem](http://en.wikipedia.org/wiki/Tmpfs), which explicitly resides in RAM only, and has the ability to expand on demand (to within some fraction of the total RAM, 50% by default, I think). This is a much better solution for high-performance pipelines, and would avoid many issues people are having on HPC systems. At the moment, this can be set in the config file, as documented on the [dedicated HPC install page](https://github.com/jdtournier/mrtrix3/wiki/Installing-on-HPC-clusters), but I'm wondering whether this wouldn't a better default overall. The only issue with this approach is that command crash, interruption, or misuse will leave temporary files lying around the `/tmp` filesystem. However, a well-configured system ought to clear these out periodically, and they won't survive a reboot anyway. 

Any opinions on the matter...?

**Comment by Lestropie** [comment]
Sounds sensible to me; it's where I always end up pointing things. It may also be worth linking to the config file wiki page at some point during each of the install page wikis. Don't think there's a sane default for this on Windows though.

Vaguely on the topic: I added a command-line option to my script library to disable the temp directory cleanup when the script completes, so you can go in there and dig around in the raw images after the fact. Comes in handy. It reads the temp directory location from the config file, so the default path when there's no config file entry should probably be the same.

**Comment by jdtournier** [comment]
> It may also be worth linking to the config file wiki page at some point during each of the install page wikis.

Good call. I'll do that in a minute.

> Don't think there's a sane default for this on Windows though.

Agree. There are a couple of options, but none are all that good. The default is within a user's account, so not great in cases where that account might be on a network share. There is a system temp folder that can probably be guaranteed local, but not sure individual users will have write permissions (there is definitely the possibility that they might not, at any rate). And none of them provide any performance guarantees (in contrast to `tmpfs`). 

Best thing to do is stick to the existing default, and document the option so they can do something about it if it becomes a problem...

> Vaguely on the topic: I added a command-line option to my script library to disable the temp directory cleanup when the script completes, so you can go in there and dig around in the raw images after the fact. Comes in handy. It reads the temp directory location from the config file, so the default path when there's no config file entry should probably be the same.

Guess I'll leave that up to you...?

**Comment by jdtournier** [comment]
Anyone else have an opinion on the matter...?

**Comment by jdtournier** [comment]
I'll take everyone's silence as a nod of approval then...

**Comment by jdtournier** [comment]
closed with 9979917

**Comment by draffelt** [comment]
Yep, I'm happy with that

On Thu, Apr 2, 2015 at 12:54 AM, J-Donald Tournier <notifications@github.com
