### ISSUE TITLE
compressed mif format not working

### ISSUE THREAD

**Issue by jdtournier** [jdtournier/mrtrix3#207]
Something that popped up while I was setting up the testing infrastructure...

Conversion to `.mif.gz` gives different values from input...

**Comment by Lestropie** [comment]
Seems to be fixed by 24c0a61...?

**Comment by Lestropie** [comment]
OK, so it's maybe kinda fixed but not entirely.
Looks like I'm relying on a hack of re-generating a text header after having read the header info into the Image::Header class, in order to produce a GZ lead-in. With the changes in #111, the input and output headers may be different lengths... let's see if this works.

**Comment by jdtournier** [comment]
OK, didn't see that one coming...

@Lestropie - Thanks for figuring this out. Not sure I like the approach though, it involves ignoring the version information on read, which means you don't see it in mrinfo... I've had a go at what is probably a cleaner approach: basically set the version info as generic header fields, which means the previous code (i.e. before the changes in #111) would simply write it out as-is without modification. It also gets read as a normal uninterpreted field, so will show up in mrinfo. To update the information, the Image::Header::create() call updates those fields with the current information - images are written out with the current version info, images read in retain the version information they were created with. 

I've also used the same approach for track files (and track_scalar files), but in this case it's the Properties that need to be updated before write-out. Haven't tested that bit, but I guess it should work fine.

I've created a new branch called `testing_alternate` with these changes. I've also cherry-picked your fixes for the MGH/MGZ formats (glad you could incorporate the NIfTI handling in there so easily, I was expecting it to get messy...). 

Let me know if you're happy with that.

**Comment by Lestropie** [comment]
Figured most commands wouldn't need access to it, but yeah didn't think of `mrinfo`. Generic header field is better then.

**Comment by jdtournier** [comment]
Cool. I'll pull the previous merge request, and merge the `testing_alternate` one to master instead. These fixes are important enough that we want them in master now, and the testing stuff really shouldn't interfere with anything anyway. We can pad it out with further tests as we go.

**Comment by jdtournier** [comment]
closed with 1050df8
