### ISSUE TITLE
copy_with_progress_message changes "date modified"

### ISSUE THREAD

**Issue by thijsdhollander** [jdtournier/mrtrix3#223]
Just remembered I had this happening a while ago.  Scenario:

1) construct a `Buffer` to access `file.mif`, based on some header
2) construct a `BufferScratch`, based on the same header
3) construct `Voxel`s for both of these
4) use `copy_with_progress_message` to copy the contents of the `Buffer` to the `BufferScratch`, providing both `Voxel`s as arguments (as well as a message `String` of course)

Result: the "date modified" of `file.mif` is changed / updated to the current time.  As far as I can tell/remember, nothing else changed to `file.mif`.

**Comment by jdtournier** [comment]
Sounds weird. Do you have a working example of this?

I'm wondering what's going on in your step 1. When you say you constructed a Buffer based on some Header, do you mean that you opened the image as a Header first, then constructed the Buffer based on that Header as the sole argument? Or did you construct a Buffer passing _both_ the header and filename? With the latter, you'd be opening the file for writing, it wouldn't be surprising if that would change the timestamp - but MRtrix shouldn't let you do that, unless you pass the `-force ` option... I'm guessing that's not what's going on...?

**Comment by thijsdhollander** [comment]
So, as I tried to regenerate it from old code, I spotted something partially fitting with what you just described (passing both the header and filename / -force was not involved).  Didn't know that would make the difference in opening it up for writing.  But it's still a bit odd, since I didn't actually pass a filename, just a string.  I'll give a structured example of what I essentially did:

`Image::Header theheader ("file.mif");`

`Image::Buffer<float> somebuffer (theheader,"something");`
`Image::BufferScratch<float> somescratch (theheader,"anything");`

`Image::Buffer<float>::voxel_type buffervoxel (somebuffer);`
`Image::BufferScratch<float>::voxel_type scratchvoxel (somescratch);`

`Image::copy_with_progress_message ("copy...", buffervoxel, scratchvoxel);`

The unintended mistake made here was copy-pasting the declaration of the `Buffer` from a declaration of a `BufferScratch` elsewhere.  The latter original declaration specified a string, so I could track the `BufferScratch` by its name when debugging.  When executing the above piece of code, a message `preloading contents of mapped file "file.mif"` appears (which also puzzled me a bit at the time).  Leaving out the string `"something"` from the above code does not generate the message nor modify the timestamp.  Although the mistake here was certainly on my part, I'm not entirely convinced it (should) make sense the above piece of code results in `file.mif`'s timestamp changing... :-)

**Comment by jdtournier** [comment]
> Although the mistake here was certainly on my part, I'm not entirely convinced it (should) make sense the above piece of code results in file.mif's timestamp changing... :-)

Fully agree... 

I guess we'll worry about this once I've finished refactoring the code as per #211, which will hopefully make the problem vanish... I'll keep an eye on this as I go though. Let's revisit after the updated syntax changes are merged.

**Comment by thijsdhollander** [comment]
> Let's revisit after the updated syntax changes are merged.

Yep, I agree.  In the mean time I did take a closer look at the debug output though, spotting several "funky" things.  Just for later reference, here are both outputs (for the correct as well as the "wrong" code).

Correct version (the previously mentioned code *without* the `"something"` string):

`[INFO] opening image "file.mif"...`
`[DEBUG] reading key/value file "file.mif"...`
`[DEBUG] sanitising image information...`
`[DEBUG] mapping image "file.mif"...`
`[DEBUG] memory-mapping file "file.mif"...`
`[DEBUG] file "file.mif" mapped at 0x7f1832572000, size 20971520 (read-only)`
`[DEBUG] image "file.mif" loaded`
`[DEBUG] voxel accessor for image "file.mif" initialised with start = 65535, strides = [ 65536 -1 -256 ]`
`[DEBUG] voxel accessor for image "anything" initialised with start = 65535, strides = [ 65536 -1 -256 ]`
`[100%] copy...`
`[DEBUG] unmapping file "file.mif"`
`[DEBUG] image "file.mif" unloaded`

"Wrong" version (the exact previously mentioned code, *including* the `"something"` string):

`[INFO] opening image "file.mif"...`
`[DEBUG] reading key/value file "file.mif"...`
`[DEBUG] sanitising image information...`
`[DEBUG] mapping image "file.mif"...`
`[DEBUG] creating RAM buffer for file "file.mif"...`
`preloading contents of mapped file "file.mif"...`
`[DEBUG] file "file.mif" held in RAM at 0x7fdcf35d6010, size 20971520`
`[DEBUG] image "file.mif" loaded`
`[DEBUG] voxel accessor for image "file.mif" initialised with start = 65535, strides = [ 65536 -1 -256 ]`
`[DEBUG] voxel accessor for image "file.mif" initialised with start = 65535, strides = [ 65536 -1 -256 ]`
`[100%] copy...`
`[INFO] writing back contents of mapped file "file.mif"...`
`[DEBUG] image "file.mif" unloaded`

There's many universe-breaking things in there, but especially the message on the initialisation of the voxel accessor for the `BufferScratch`, mentioning `"file.mif"` out of the blue is... weird.

**Comment by jdtournier** [comment]
Yup, lots of weird things going on here... But I think it boils down to some over-zealous type conversion, which we could/should fix by marking the constructors `explicit`. Looking at the constructors for Image::Buffer, the only one it could match is `Buffer (const Header& header, bool readwrite = false)` - it just decided to cast your `const char*` into a `bool`...

All the preloading, etc is about handling of a read/write image. Read/write access is no longer done using memory-mapping, since updating the image data on a memory-mapped file can cause serious performance issues if that file resides on a networked filesystem. So we create a RAM buffer to hold the data, and write back in the destructor. Since you opened an _existing_ image read/write, it also needs to load the existing data into the buffer, rather than simply zeroing it (which would be what happens normally for a pure output image). 

So I reckon it all makes sense, and is easily fixed with an additional `explicit` in the right places...
