### ISSUE TITLE
MRView: lightbox mode grid not aligned with images

### ISSUE THREAD

**Issue by jdtournier** [jdtournier/mrtrix3#224]
Just noticed this (on up to date master branch): opening an  image with the lightbox mode and zooming in, you can see that the grid isn't aligned with the images themselves, _if_ a tool is docked in the main window - see attached. As soon at the tool is hidden or detached from the main window, things come back into alignment...

![screenshot0000](https://cloud.githubusercontent.com/assets/3221000/7248442/8fa5e1e2-e80a-11e4-9997-2c42911db14c.png)

**Comment by rtabbara** [comment]
@jdtournier Think this is sorted now. Please take a look at let me know.

**Comment by jdtournier** [comment]
Yup, seems fixed to me with c08395b.
