### ISSUE TITLE
MRview: Issues on mac

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#34]
(As reported by Daan Christiaens)

1. Tractography panel: setting the line thickness does not work, no matter what I do with the slider.

2. If I load a new track file in the GUI, it doesn't appear until I select it in the list. The box to the left of the file name is checked, but it only shows up if I click on the name.

3. If I load a track file on launching the viewer, using mrview image.mif -run tractography.load tracks.tck (really great that we can do this now!), I get an error:
```
mrview [ERROR]: /mrtrix/mrtrix3/blob/master/unknown format for image "tracks.tck"
mrview [ERROR]: /mrtrix/mrtrix3/blob/master/error opening image "tracks.tck"
mrview [WARNING]: /mrtrix/mrtrix3/blob/master/batch command "tractography.load" unclaimed by main window or any active tool - ignored
```

4. ODF display works only up to order 8. For order 10, I get nothing but a mess of black lines in the side panel.

5. With the apple "magic mouse", I can't scroll from one slice to the next. The arrow keys and an old non-apple mouse work fine. Despite that, I found the viewer very useable with the magic mouse, thanks to the separate "mouse modes". Definitely a large improvement over mrtrix2 :)

6. If I mistakenly hold the Ctrl button while using the mouse, the terminal fills with messages "QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)". Due to the keyboard layout on Mac, I get this quite a lot and it can get a little annoying.

**Comment by jdtournier** [comment]
I'll close this for now, I think most issues have been addressed or are due to Qt quirkiness...
