### ISSUE TITLE
Transform modifier for screen capture - translation

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#35]
Currently the translate option in screen capture mode operates in scanner space coordinates. This makes it unnecessarily difficult to generate a movie that e.g. rasters through the slice stack, which was the main application for this feature in 0.2.

A check box should be adequate to flag that the desired translation is provided in voxel space rather than real space. Though this still requires multiplication of the voxel size with the number of slices to get the desired effect...

**Comment by rtabbara** [comment]
Had a go at this &mdash; please let me know if it's the desired behaviour.

By default, I've set translations to be in terms of voxel space coordinates, with a check box allowing you to toggle to scanner space.

**Comment by jdtournier** [comment]
Looks good, thanks for that. I've made a couple of tiny edits, which are just me being pedantic...

Would be great to do something about the rotation axis too. I'll go create an issue about that.

**Comment by jdtournier** [comment]
closed with 5b6b91f
