### ISSUE TITLE
Modify vector plot to display SH peaks and eigenvectors

### ISSUE THREAD

**Issue by draffelt** [jdtournier/mrtrix3#65]

**Comment by rtabbara** [comment]
The Vector plot tool should now be able to open non-msf files.

* The open file dialog allows you to select to filter between MRtrix sparse or Medical Images.

* In the latter case, there's some sanity checking in place when opening to ensure that the image selected indeed is a vector image.

* As mentioned in the discussion, a consequence of gelling with the layout of <code>FixelMetric</code> means that for non-spare images, the choice of scaling by 'Fixel Size' or 'Associated value' will both coincide with the norm of the vector.
